#' Title
#'
#' @param df Patient info
#' @param comorb_string .
#' @param drug_string .
#' @param diastolic_column .
#' @param systolic_column .
#' @param age_column .
#' @param HR_column .
#' @param K_column .
#' @param gender_column .
#'
#' @return Data frame of character vectors.
#' @export
#'
#' @examples all_stoppstart(session13)
all_stoppstart <- function(df, comorb_string = "Comorbidity_",
                           drug_string = "Drug_",
                           diastolic_column = "Diastolic_BP",
                           systolic_column = "Systolic_BP",
                           age_column = "Age",
                           HR_column = "HR_column",
                           K_column = "K_column",
                           gender_column = "Gender") {
  starts <- data.frame(
    a1 = start_a1(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    a3 = start_a3(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    a4 = start_a4(df,
                  comorb_string = comorb_string, drug_string = drug_string,
                  diastolic_column = diastolic_column,
                  systolic_column = systolic_column),
    a5 = start_a5(df,
                  comorb_string = comorb_string, drug_string = drug_string,
                  age_column = age_column),
    a6 = start_a6(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    a7 = start_a7(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    a8 = start_a8(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    b1 = start_b1(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    c1 = start_c1(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    c2 = start_c2(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    c4 = start_c4(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    c5 = start_c5(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    c6 = start_c6(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    d1 = start_d1(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    d2 = start_d2(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    e1 = start_e1(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    e2 = start_e2(df,
                  drug_string = drug_string),
    e4 = start_e4(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    e6 = start_e6(df,
                  comorb_string = comorb_string, drug_string = drug_string),
    e7 = start_e7(df,
                  drug_string = drug_string),
    g1 = start_g1(df,
                  comorb_string = comorb_string, drug_string = drug_string,
                  gender_column = gender_column),
    g2 = start_g2(df,
                  comorb_string = comorb_string, drug_string = drug_string,
                  gender_column = gender_column),
    g3 = start_g3(df,
                  comorb_string = comorb_string, drug_string = drug_string,
                  gender_column = gender_column),
    h2 = start_h2(df,
                  drug_string = drug_string),
    s_b1 = stopp_b1(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_b2 = stopp_b2(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_b3 = stopp_b3(df,
                    drug_string = drug_string),
    s_b4 = stopp_b4(df,
                    comorb_string = comorb_string, drug_string = drug_string,
                    HR_column = "Lab Values: Heart Rate"),
    s_b5 = stopp_b5(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_b6 = stopp_b6(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_b7 = stopp_b7(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_b9 = stopp_b9(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_b10 = stopp_b10(df,
                    drug_string = drug_string),
    s_b11 = stopp_b11(df,
                    comorb_string = comorb_string, drug_string = drug_string,
                    K_column = "Lab Values: K"),
    s_c2 = stopp_c2(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_c5 = stopp_c5(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_c7 = stopp_c7(df,
                      drug_string = drug_string),
    s_c8 = stopp_c8(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_c10 = stopp_c10(df,
                      drug_string = drug_string),
    s_c11 = stopp_c11(df,
                      drug_string = drug_string),
    s_d1 = stopp_d1(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_d3 = stopp_d3(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_d5 = stopp_d5(df,
                    drug_string = drug_string),
    s_d8 = stopp_d8(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_d12 = stopp_d12(df,
                    drug_string = drug_string),
    s_d14 = stopp_d14(df,
                    drug_string = drug_string),
    s_f1 = stopp_f1(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_f3 = stopp_f3(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_g1 = stopp_g1(df,
                  drug_string = drug_string),
    s_g2 = stopp_g2(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_h1 = stopp_h1(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_h2 = stopp_h2(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_h4 = stopp_h4(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_h5 = stopp_h5(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_h6 = stopp_h6(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_h7 = stopp_h7(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_h8 = stopp_h8(df,
                    drug_string = drug_string),
    s_h9 = stopp_h9(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_i2 = stopp_i2(df,
                    comorb_string = comorb_string, drug_string = drug_string),
    s_j1 = stopp_j1(df,
                    drug_string = drug_string)


  )

  return(starts)
}
